"""Preparation and E1 entity-cell localization contracts."""

from .analysis import (
    anonymous_progress,
    collision_selectivity_summary,
    denominator_eligibility,
    held_variant_metrics,
    summarize_amnesia,
    surface_control_summary,
    trusted_candidate_eligibility,
)
from .mlp_cells import (
    ALPHA_GRID,
    CANDIDATE_LAYERS,
    EPSILON,
    MLPHookSession,
    OnlineVectorStats,
    collect_generic_stats,
    mlp_hooks,
    rank_stability_scores,
    record_post_swiglu,
    run_amnesia_curve,
    select_matched_random_neuron,
    surface_form_controls,
)
from .pipeline import DATASET, STAGES, run_e1
from .e2 import E2_ALL_STAGES, E2_READOUT_STAGE, E2_STAGES, analyze_e2, run_e2
from .e3 import E3_ANALYZE_STAGE, E3_STAGES, analyze_e3, analyze_e3_records, run_downstream_suppression_record, run_e3, run_upstream_suppression_record
from .suppression import (
    E3_ALPHA_GRID, E3_BETA_GRID, SOURCE_NORM_EPSILON, AttenuationControl,
    SourceAttenuationSession, attenuate_identity_sources,
    compute_source_attenuation_deltas, deterministic_source_subset,
    e3_compact_record, e3_progress, matched_perturbation_norm,
    norm_matched_source_delta, preservation_metrics,
    reconstruct_source_components, source_resolved_head_inputs,
    validate_dose_grid, whole_head_upper_bound_beta,
)
from .readout import (
    ARTIFACT_TYPE as E2_READOUT_ARTIFACT_TYPE,
    DEFAULT_READOUT_CONFIG,
    DEFAULT_SECTOR_VOCABULARY,
    compact_selected_component_readout,
    readout_component,
    readout_selected_component,
    unavailable_component_readout,
)
from .attention_attribution import (
    FULL_ATTENTION_LAYERS,
    PRIMARY_ATTENTION_LAYERS,
    SOURCE_GROUPS,
    AttentionReconstruction,
    compact_attribution_record,
    contract_dla,
    direct_logit_attribution,
    frozen_margin_direction,
    patch_head_output,
    rank_attention_heads,
    reconstruct_attention_components,
    resolve_single_token_pair,
    routing_label,
    selected_head_output_patch,
    validate_attention_layers,
)
from .preparation import (
    BASELINE_RECORD_COUNT,
    FINANCIAL_PROMPT_COLUMNS,
    HEADER_VARIANT_COUNT,
    HEADER_VARIANT_SPECS,
    LOCALIZATION_VARIANT_IDS,
    HELD_VARIANT_IDS,
    prepare_inputs,
    prepare_artifacts,
    render_header_variants,
    validate_baseline_contract,
    validate_prepared_inputs,
)

__all__ = [
    "BASELINE_RECORD_COUNT",
    "FINANCIAL_PROMPT_COLUMNS",
    "HEADER_VARIANT_COUNT",
    "HEADER_VARIANT_SPECS",
    "LOCALIZATION_VARIANT_IDS",
    "HELD_VARIANT_IDS",
    "prepare_inputs",
    "prepare_artifacts",
    "render_header_variants",
    "validate_baseline_contract",
    "validate_prepared_inputs",
    "ALPHA_GRID",
    "CANDIDATE_LAYERS",
    "EPSILON",
    "MLPHookSession",
    "OnlineVectorStats",
    "anonymous_progress",
    "collision_selectivity_summary",
    "collect_generic_stats",
    "denominator_eligibility",
    "held_variant_metrics",
    "mlp_hooks",
    "rank_stability_scores",
    "record_post_swiglu",
    "run_amnesia_curve",
    "run_e1",
    "select_matched_random_neuron",
    "surface_control_summary",
    "surface_form_controls",
    "summarize_amnesia",
    "trusted_candidate_eligibility",
    "DATASET",
    "STAGES",
    "E2_STAGES",
    "E2_READOUT_STAGE",
    "E2_ALL_STAGES",
    "run_e2",
    "E3_ANALYZE_STAGE", "E3_STAGES", "analyze_e3", "analyze_e3_records", "run_downstream_suppression_record", "run_e3", "run_upstream_suppression_record",
    "E3_ALPHA_GRID", "E3_BETA_GRID", "SOURCE_NORM_EPSILON", "AttenuationControl", "SourceAttenuationSession", "attenuate_identity_sources", "compute_source_attenuation_deltas", "deterministic_source_subset", "e3_compact_record", "e3_progress", "matched_perturbation_norm", "norm_matched_source_delta", "preservation_metrics", "reconstruct_source_components", "source_resolved_head_inputs", "validate_dose_grid", "whole_head_upper_bound_beta",
    "analyze_e2",
    "FULL_ATTENTION_LAYERS",
    "PRIMARY_ATTENTION_LAYERS",
    "SOURCE_GROUPS",
    "AttentionReconstruction",
    "compact_attribution_record",
    "contract_dla",
    "direct_logit_attribution",
    "frozen_margin_direction",
    "patch_head_output",
    "rank_attention_heads",
    "reconstruct_attention_components",
    "resolve_single_token_pair",
    "routing_label",
    "selected_head_output_patch",
    "validate_attention_layers",
    "E2_READOUT_ARTIFACT_TYPE",
    "DEFAULT_READOUT_CONFIG",
    "DEFAULT_SECTOR_VOCABULARY",
    "compact_selected_component_readout",
    "readout_component",
    "readout_selected_component",
    "unavailable_component_readout",
]
